var assert = require('assert'),
    jsc = require('jscoverage'),
    // require = require(module),
    CrossWords = require('../crosswords.js', true),
    game = new CrossWords();

module.exports = {
  'options.startUpOptions': function () {
    assert.eql([], game.words);
    assert.eql([], game.possiblePositions);
    assert.equal('*', game.crossWordSignal);
    assert.equal(10, game.maxWordLength);
    assert.equal(100, game.maxWordSlots);
    assert.equal(100, game.remainingSlots);
    assert.equal(true, game.prettyPrint);
    assert.equal(false, game.wordsShortCut);
    assert.equal(10, game.crossWord.length);
  },
  'methods.registerWordsOnBoard.searchFreeSlotByLine()': function () {
     game = new CrossWords();
      //                   0123456789
      game.crossWord[0] = "TESTE***Y*";
      game.crossWord[1] = "*E******A*";
      game.crossWord[2] = "**S*****H*";
      game.crossWord[3] = "***T****O*";
      game.crossWord[4] = "****E***O*";
      game.crossWord[5] = "**********";
      game.crossWord[6] = "**********";
      game.crossWord[7] = "**********";
      game.crossWord[8] = "**********";
      game.crossWord[9] = "**********";

      assert.deepEqual(game.registerWordsOnBoard().searchFreeSlotByLine(game.crossWord[0], 'BRA', 0), [5,7]);
      assert.deepEqual(game.registerWordsOnBoard().searchFreeSlotByLine(game.crossWord[5], 'YAHOO', 0), [0,4]);
      assert.deepEqual(game.registerWordsOnBoard().searchFreeSlotByLine(game.crossWord[1], 'YAHOO', 0), [2,6]);
      assert.deepEqual(game.registerWordsOnBoard().searchFreeSlotByLine(game.crossWord[6], 'PERNAMBUCO', 0), [0,9]);

  },
  'methods.registerWordsOnBoard.searchFreeSlot()': function () {
     game = new CrossWords();

      //                   0123456789
      game.crossWord[0] = "TESTE***Y*";
      game.crossWord[1] = "*E******A*";
      game.crossWord[2] = "**S*****H*";
      game.crossWord[3] = "***T****O*";
      game.crossWord[4] = "****E***O*";
      game.crossWord[5] = "**********";
      game.crossWord[6] = "**********";
      game.crossWord[7] = "**********";
      game.crossWord[8] = "**********";
      game.crossWord[9] = "**********";

      assert.deepEqual(game.registerWordsOnBoard().searchFreeSlot('PERNAMBUCO'), [ 
        { direction: 'h', position: 5, word: 'PERNAMBUCO', coord: [ 0, 9 ] },
        { direction: 'h', position: 6, word: 'PERNAMBUCO', coord: [ 0, 9 ] },
        { direction: 'h', position: 7, word: 'PERNAMBUCO', coord: [ 0, 9 ] },
        { direction: 'h', position: 8, word: 'PERNAMBUCO', coord: [ 0, 9 ] },
        { direction: 'h', position: 9, word: 'PERNAMBUCO', coord: [ 0, 9 ] },
        { direction: 'v', position: 5, word: 'PERNAMBUCO', coord: [ 0, 9 ] },
        { direction: 'v', position: 6, word: 'PERNAMBUCO', coord: [ 0, 9 ] },
        { direction: 'v', position: 7, word: 'PERNAMBUCO', coord: [ 0, 9 ] },
        { direction: 'v', position: 9, word: 'PERNAMBUCO', coord: [ 0, 9 ] } ]);
  
    //                   0123456789
    game.crossWord[0] = "TESTE***Y*";
    game.crossWord[1] = "********A*";
    game.crossWord[2] = "**M*****H*";
    game.crossWord[3] = "**E*****O*";
    game.crossWord[4] = "**M*****O*";
    game.crossWord[5] = "**E*******";
    game.crossWord[6] = "**********";
    game.crossWord[7] = "**********";
    game.crossWord[8] = "**********";
    game.crossWord[9] = "**********";

  assert.deepEqual(game.registerWordsOnBoard().searchFreeSlot('AMOR'), [ 
    { direction: 'h', position: 1, word: 'AMOR', coord: [ 0, 3 ] },
    { direction: 'h', position: 1, word: 'AMOR', coord: [ 1, 4 ] },
    { direction: 'h', position: 1, word: 'AMOR', coord: [ 2, 5 ] },
    { direction: 'h', position: 1, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'h', position: 1, word: 'AMOR', coord: [ 4, 7 ] },
    { direction: 'h', position: 2, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'h', position: 2, word: 'AMOR', coord: [ 1, 4 ] },
    { direction: 'h', position: 2, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'h', position: 2, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'h', position: 2, word: 'AMOR', coord: [ 4, 7 ] },
    { direction: 'h', position: 3, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'h', position: 3, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'h', position: 3, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'h', position: 3, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'h', position: 3, word: 'AMOR', coord: [ 4, 7 ] },
    { direction: 'h', position: 3, word: 'AMOR', coord: [ 6, 9 ] },
    { direction: 'h', position: 4, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'h', position: 4, word: 'AMOR', coord: [ 1, 4 ] },
    { direction: 'h', position: 4, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'h', position: 4, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'h', position: 4, word: 'AMOR', coord: [ 4, 7 ] },
    { direction: 'h', position: 4, word: 'AMOR', coord: [ 6, 9 ] },
    { direction: 'h', position: 5, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'h', position: 5, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'h', position: 5, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'h', position: 5, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'h', position: 5, word: 'AMOR', coord: [ 4, 7 ] },
    { direction: 'h', position: 5, word: 'AMOR', coord: [ 5, 8 ] },
    { direction: 'h', position: 5, word: 'AMOR', coord: [ 6, 9 ] },
    { direction: 'h', position: 6, word: 'AMOR', coord: [ 0, 3 ] },
    { direction: 'h', position: 6, word: 'AMOR', coord: [ 1, 4 ] },
    { direction: 'h', position: 6, word: 'AMOR', coord: [ 2, 5 ] },
    { direction: 'h', position: 6, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'h', position: 6, word: 'AMOR', coord: [ 4, 7 ] },
    { direction: 'h', position: 6, word: 'AMOR', coord: [ 5, 8 ] },
    { direction: 'h', position: 6, word: 'AMOR', coord: [ 6, 9 ] },
    { direction: 'h', position: 7, word: 'AMOR', coord: [ 0, 3 ] },
    { direction: 'h', position: 7, word: 'AMOR', coord: [ 1, 4 ] },
    { direction: 'h', position: 7, word: 'AMOR', coord: [ 2, 5 ] },
    { direction: 'h', position: 7, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'h', position: 7, word: 'AMOR', coord: [ 4, 7 ] },
    { direction: 'h', position: 7, word: 'AMOR', coord: [ 5, 8 ] },
    { direction: 'h', position: 7, word: 'AMOR', coord: [ 6, 9 ] },
    { direction: 'h', position: 8, word: 'AMOR', coord: [ 0, 3 ] },
    { direction: 'h', position: 8, word: 'AMOR', coord: [ 1, 4 ] },
    { direction: 'h', position: 8, word: 'AMOR', coord: [ 2, 5 ] },
    { direction: 'h', position: 8, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'h', position: 8, word: 'AMOR', coord: [ 4, 7 ] },
    { direction: 'h', position: 8, word: 'AMOR', coord: [ 5, 8 ] },
    { direction: 'h', position: 8, word: 'AMOR', coord: [ 6, 9 ] },
    { direction: 'h', position: 9, word: 'AMOR', coord: [ 0, 3 ] },
    { direction: 'h', position: 9, word: 'AMOR', coord: [ 1, 4 ] },
    { direction: 'h', position: 9, word: 'AMOR', coord: [ 2, 5 ] },
    { direction: 'h', position: 9, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'h', position: 9, word: 'AMOR', coord: [ 4, 7 ] },
    { direction: 'h', position: 9, word: 'AMOR', coord: [ 5, 8 ] },
    { direction: 'h', position: 9, word: 'AMOR', coord: [ 6, 9 ] },
    { direction: 'v', position: 0, word: 'AMOR', coord: [ 1, 4 ] },
    { direction: 'v', position: 0, word: 'AMOR', coord: [ 1, 4 ] },
    { direction: 'v', position: 0, word: 'AMOR', coord: [ 2, 5 ] },
    { direction: 'v', position: 0, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'v', position: 0, word: 'AMOR', coord: [ 4, 7 ] },
    { direction: 'v', position: 0, word: 'AMOR', coord: [ 5, 8 ] },
    { direction: 'v', position: 0, word: 'AMOR', coord: [ 6, 9 ] },
    { direction: 'v', position: 1, word: 'AMOR', coord: [ 1, 4 ] },
    { direction: 'v', position: 1, word: 'AMOR', coord: [ 1, 4 ] },
    { direction: 'v', position: 1, word: 'AMOR', coord: [ 2, 5 ] },
    { direction: 'v', position: 1, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'v', position: 1, word: 'AMOR', coord: [ 4, 7 ] },
    { direction: 'v', position: 1, word: 'AMOR', coord: [ 5, 8 ] },
    { direction: 'v', position: 1, word: 'AMOR', coord: [ 6, 9 ] },
    { direction: 'v', position: 2, word: 'AMOR', coord: [ 6, 9 ] },
    { direction: 'v', position: 2, word: 'AMOR', coord: [ 6, 9 ] },
    { direction: 'v', position: 2, word: 'AMOR', coord: [ 6, 9 ] },
    { direction: 'v', position: 2, word: 'AMOR', coord: [ 6, 9 ] },
    { direction: 'v', position: 2, word: 'AMOR', coord: [ 6, 9 ] },
    { direction: 'v', position: 2, word: 'AMOR', coord: [ 6, 9 ] },
    { direction: 'v', position: 2, word: 'AMOR', coord: [ 6, 9 ] },
    { direction: 'v', position: 3, word: 'AMOR', coord: [ 1, 4 ] },
    { direction: 'v', position: 3, word: 'AMOR', coord: [ 1, 4 ] },
    { direction: 'v', position: 3, word: 'AMOR', coord: [ 2, 5 ] },
    { direction: 'v', position: 3, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'v', position: 3, word: 'AMOR', coord: [ 4, 7 ] },
    { direction: 'v', position: 3, word: 'AMOR', coord: [ 5, 8 ] },
    { direction: 'v', position: 3, word: 'AMOR', coord: [ 6, 9 ] },
    { direction: 'v', position: 4, word: 'AMOR', coord: [ 1, 4 ] },
    { direction: 'v', position: 4, word: 'AMOR', coord: [ 1, 4 ] },
    { direction: 'v', position: 4, word: 'AMOR', coord: [ 2, 5 ] },
    { direction: 'v', position: 4, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'v', position: 4, word: 'AMOR', coord: [ 4, 7 ] },
    { direction: 'v', position: 4, word: 'AMOR', coord: [ 5, 8 ] },
    { direction: 'v', position: 4, word: 'AMOR', coord: [ 6, 9 ] },
    { direction: 'v', position: 5, word: 'AMOR', coord: [ 0, 3 ] },
    { direction: 'v', position: 5, word: 'AMOR', coord: [ 1, 4 ] },
    { direction: 'v', position: 5, word: 'AMOR', coord: [ 2, 5 ] },
    { direction: 'v', position: 5, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'v', position: 5, word: 'AMOR', coord: [ 4, 7 ] },
    { direction: 'v', position: 5, word: 'AMOR', coord: [ 5, 8 ] },
    { direction: 'v', position: 5, word: 'AMOR', coord: [ 6, 9 ] },
    { direction: 'v', position: 6, word: 'AMOR', coord: [ 0, 3 ] },
    { direction: 'v', position: 6, word: 'AMOR', coord: [ 1, 4 ] },
    { direction: 'v', position: 6, word: 'AMOR', coord: [ 2, 5 ] },
    { direction: 'v', position: 6, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'v', position: 6, word: 'AMOR', coord: [ 4, 7 ] },
    { direction: 'v', position: 6, word: 'AMOR', coord: [ 5, 8 ] },
    { direction: 'v', position: 6, word: 'AMOR', coord: [ 6, 9 ] },
    { direction: 'v', position: 7, word: 'AMOR', coord: [ 0, 3 ] },
    { direction: 'v', position: 7, word: 'AMOR', coord: [ 1, 4 ] },
    { direction: 'v', position: 7, word: 'AMOR', coord: [ 2, 5 ] },
    { direction: 'v', position: 7, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'v', position: 7, word: 'AMOR', coord: [ 4, 7 ] },
    { direction: 'v', position: 7, word: 'AMOR', coord: [ 5, 8 ] },
    { direction: 'v', position: 7, word: 'AMOR', coord: [ 6, 9 ] },
    { direction: 'v', position: 8, word: 'AMOR', coord: [ 5, 8 ] },
    { direction: 'v', position: 8, word: 'AMOR', coord: [ 5, 8 ] },
    { direction: 'v', position: 8, word: 'AMOR', coord: [ 5, 8 ] },
    { direction: 'v', position: 8, word: 'AMOR', coord: [ 5, 8 ] },
    { direction: 'v', position: 8, word: 'AMOR', coord: [ 5, 8 ] },
    { direction: 'v', position: 8, word: 'AMOR', coord: [ 5, 8 ] },
    { direction: 'v', position: 8, word: 'AMOR', coord: [ 6, 9 ] },
    { direction: 'v', position: 9, word: 'AMOR', coord: [ 0, 3 ] },
    { direction: 'v', position: 9, word: 'AMOR', coord: [ 1, 4 ] },
    { direction: 'v', position: 9, word: 'AMOR', coord: [ 2, 5 ] },
    { direction: 'v', position: 9, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'v', position: 9, word: 'AMOR', coord: [ 4, 7 ] },
    { direction: 'v', position: 9, word: 'AMOR', coord: [ 5, 8 ] },
    { direction: 'v', position: 9, word: 'AMOR', coord: [ 6, 9 ] },
    { direction: 'd', position: 0, word: 'AMOR', coord: [ 1, 4 ] },
    { direction: 'd', position: 0, word: 'AMOR', coord: [ 1, 4 ] },
    { direction: 'd', position: 0, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'd', position: 0, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'd', position: 0, word: 'AMOR', coord: [ 4, 7 ] },
    { direction: 'd', position: 0, word: 'AMOR', coord: [ 5, 8 ] },
    { direction: 'd', position: 0, word: 'AMOR', coord: [ 6, 9 ] },
    { direction: 'd', position: 1, word: 'AMOR', coord: [ 1, 4 ] },
    { direction: 'd', position: 1, word: 'AMOR', coord: [ 1, 4 ] },
    { direction: 'd', position: 1, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'd', position: 1, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'd', position: 1, word: 'AMOR', coord: [ 4, 7 ] },
    { direction: 'd', position: 1, word: 'AMOR', coord: [ 5, 8 ] },
    { direction: 'd', position: 1, word: 'AMOR', coord: [ 6, 9 ] },
    { direction: 'd', position: 2, word: 'AMOR', coord: [ 1, 4 ] },
    { direction: 'd', position: 2, word: 'AMOR', coord: [ 1, 4 ] },
    { direction: 'd', position: 2, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'd', position: 2, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'd', position: 2, word: 'AMOR', coord: [ 4, 7 ] },
    { direction: 'd', position: 2, word: 'AMOR', coord: [ 5, 8 ] },
    { direction: 'd', position: 2, word: 'AMOR', coord: [ 6, 9 ] },
    { direction: 'd', position: 3, word: 'AMOR', coord: [ 1, 4 ] },
    { direction: 'd', position: 3, word: 'AMOR', coord: [ 1, 4 ] },
    { direction: 'd', position: 3, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'd', position: 3, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'd', position: 3, word: 'AMOR', coord: [ 4, 7 ] },
    { direction: 'd', position: 3, word: 'AMOR', coord: [ 5, 8 ] },
    { direction: 'd', position: 3, word: 'AMOR', coord: [ 6, 9 ] },
    { direction: 'd', position: 4, word: 'AMOR', coord: [ 1, 4 ] },
    { direction: 'd', position: 4, word: 'AMOR', coord: [ 1, 4 ] },
    { direction: 'd', position: 4, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'd', position: 4, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'd', position: 4, word: 'AMOR', coord: [ 4, 7 ] },
    { direction: 'd', position: 4, word: 'AMOR', coord: [ 5, 8 ] },
    { direction: 'd', position: 4, word: 'AMOR', coord: [ 6, 9 ] },
    { direction: 'd', position: 5, word: 'AMOR', coord: [ 1, 4 ] },
    { direction: 'd', position: 5, word: 'AMOR', coord: [ 1, 4 ] },
    { direction: 'd', position: 5, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'd', position: 5, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'd', position: 5, word: 'AMOR', coord: [ 4, 7 ] },
    { direction: 'd', position: 5, word: 'AMOR', coord: [ 5, 8 ] },
    { direction: 'd', position: 5, word: 'AMOR', coord: [ 6, 9 ] },
    { direction: 'd', position: 6, word: 'AMOR', coord: [ 1, 4 ] },
    { direction: 'd', position: 6, word: 'AMOR', coord: [ 1, 4 ] },
    { direction: 'd', position: 6, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'd', position: 6, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'd', position: 6, word: 'AMOR', coord: [ 4, 7 ] },
    { direction: 'd', position: 6, word: 'AMOR', coord: [ 5, 8 ] },
    { direction: 'd', position: 6, word: 'AMOR', coord: [ 6, 9 ] },
    { direction: 'd', position: 7, word: 'AMOR', coord: [ 1, 4 ] },
    { direction: 'd', position: 7, word: 'AMOR', coord: [ 1, 4 ] },
    { direction: 'd', position: 7, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'd', position: 7, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'd', position: 7, word: 'AMOR', coord: [ 4, 7 ] },
    { direction: 'd', position: 7, word: 'AMOR', coord: [ 5, 8 ] },
    { direction: 'd', position: 7, word: 'AMOR', coord: [ 6, 9 ] },
    { direction: 'd', position: 8, word: 'AMOR', coord: [ 1, 4 ] },
    { direction: 'd', position: 8, word: 'AMOR', coord: [ 1, 4 ] },
    { direction: 'd', position: 8, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'd', position: 8, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'd', position: 8, word: 'AMOR', coord: [ 4, 7 ] },
    { direction: 'd', position: 8, word: 'AMOR', coord: [ 5, 8 ] },
    { direction: 'd', position: 8, word: 'AMOR', coord: [ 6, 9 ] },
    { direction: 'd', position: 9, word: 'AMOR', coord: [ 1, 4 ] },
    { direction: 'd', position: 9, word: 'AMOR', coord: [ 1, 4 ] },
    { direction: 'd', position: 9, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'd', position: 9, word: 'AMOR', coord: [ 3, 6 ] },
    { direction: 'd', position: 9, word: 'AMOR', coord: [ 4, 7 ] },
    { direction: 'd', position: 9, word: 'AMOR', coord: [ 5, 8 ] },
    { direction: 'd', position: 9, word: 'AMOR', coord: [ 6, 9 ] } ]);

  },
  'methods.registerWordsOnBoard.getColumn()': function () {
      game = new CrossWords();

      game.crossWord[0] = "TESTE***Y*";
      game.crossWord[1] = "*E******A*";
      game.crossWord[2] = "**S*****H*";
      game.crossWord[3] = "***T****O*";
      game.crossWord[4] = "****E***O*";
      game.crossWord[5] = "**********";
      game.crossWord[6] = "**********";
      game.crossWord[7] = "**********";
      game.crossWord[8] = "**********";
      game.crossWord[9] = "**********";

      assert.equal(game.registerWordsOnBoard().getColumn(0, 'h'), 'TESTE***Y*');
      assert.equal(game.registerWordsOnBoard().getColumn(8, 'v'), 'YAHOO*****');
      assert.equal(game.registerWordsOnBoard().getColumn(0, 'd'), 'TESTE*****');
  },
  'methods.drawCrossWord()': function () {
    var drawedCrossWord =  game.drawCrossWord();
    assert.equal(10, drawedCrossWord.length);
    drawedCrossWord.forEach(function(drawed){
      assert.equal('**********', drawed);
    }); 
  },
  'methods.prepareWord()': function () {
    assert.equal('ABC', game.prepareWord('abc'));
    assert.equal('ABC', game.prepareWord('a-b-c'));
    assert.equal('ABC', game.prepareWord('a   b    c'));
    assert.equal('BC', game.prepareWord('ábác'));
  },
  'methods.validateWord()': function () {
    assert.equal("Your word 'palavramaiorque10chars' can't be higher than 10 chars.\n",
    game.validateWord('palavramaiorque10chars').error);
    game.remainingSlots = 0;

    assert.equal("The word palavra' wasn't added. No slots available!\n",
    game.validateWord('palavra').error);
    game = new CrossWords(); // reseting classes
  },
  'methods.processTypedWords()': function () {
    game.processTypedWords('yahoo,meme,poker');

    assert.equal(3, game.words.length); 
    assert.equal(86, game.remainingSlots);
  },
  'methods.orderByLength()': function () {
    assert.equal('yahoo', game.orderByLength(['a', 'bc', 'yahoo'])[0]); 
  },
  'methods.registerWord()': function () {
    game = new CrossWords();

    assert.deepEqual(['SMALL'], game.registerWord('small'));
    assert.deepEqual("Your word 'SUPERBIGWORD' can't be higher than 10 chars.\n", game.registerWord('superbigword'));
  },
  'methods.registerWordsOnBoard().smallWords': function () {
    game = new CrossWords();
    game.randomPositions = false;

    game.processTypedWords('yahoo,meme,poker');
    game.registerWordsOnBoard();

    assert.deepEqual(['POKER', 'YAHOO', 'MEME'], game.words);
    assert.deepEqual(
      ["POKERYAHOO",
       "MEME******",
       "**********",
       "**********",
       "**********",
       "**********",
       "**********",
       "**********",
       "**********",
       "**********"], game.crossWord);

    assert.eql(game.possiblePositions['MEME'], [ 
      { direction: 'h', position: 1, word: 'MEME', coord: [ 0, 3 ] },
      { direction: 'h', position: 1, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'h', position: 1, word: 'MEME', coord: [ 2, 5 ] },
      { direction: 'h', position: 1, word: 'MEME', coord: [ 3, 6 ] },
      { direction: 'h', position: 1, word: 'MEME', coord: [ 4, 7 ] },
      { direction: 'h', position: 1, word: 'MEME', coord: [ 5, 8 ] },
      { direction: 'h', position: 1, word: 'MEME', coord: [ 6, 9 ] },
      { direction: 'h', position: 2, word: 'MEME', coord: [ 0, 3 ] },
      { direction: 'h', position: 2, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'h', position: 2, word: 'MEME', coord: [ 2, 5 ] },
      { direction: 'h', position: 2, word: 'MEME', coord: [ 3, 6 ] },
      { direction: 'h', position: 2, word: 'MEME', coord: [ 4, 7 ] },
      { direction: 'h', position: 2, word: 'MEME', coord: [ 5, 8 ] },
      { direction: 'h', position: 2, word: 'MEME', coord: [ 6, 9 ] },
      { direction: 'h', position: 3, word: 'MEME', coord: [ 0, 3 ] },
      { direction: 'h', position: 3, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'h', position: 3, word: 'MEME', coord: [ 2, 5 ] },
      { direction: 'h', position: 3, word: 'MEME', coord: [ 3, 6 ] },
      { direction: 'h', position: 3, word: 'MEME', coord: [ 4, 7 ] },
      { direction: 'h', position: 3, word: 'MEME', coord: [ 5, 8 ] },
      { direction: 'h', position: 3, word: 'MEME', coord: [ 6, 9 ] },
      { direction: 'h', position: 4, word: 'MEME', coord: [ 0, 3 ] },
      { direction: 'h', position: 4, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'h', position: 4, word: 'MEME', coord: [ 2, 5 ] },
      { direction: 'h', position: 4, word: 'MEME', coord: [ 3, 6 ] },
      { direction: 'h', position: 4, word: 'MEME', coord: [ 4, 7 ] },
      { direction: 'h', position: 4, word: 'MEME', coord: [ 5, 8 ] },
      { direction: 'h', position: 4, word: 'MEME', coord: [ 6, 9 ] },
      { direction: 'h', position: 5, word: 'MEME', coord: [ 0, 3 ] },
      { direction: 'h', position: 5, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'h', position: 5, word: 'MEME', coord: [ 2, 5 ] },
      { direction: 'h', position: 5, word: 'MEME', coord: [ 3, 6 ] },
      { direction: 'h', position: 5, word: 'MEME', coord: [ 4, 7 ] },
      { direction: 'h', position: 5, word: 'MEME', coord: [ 5, 8 ] },
      { direction: 'h', position: 5, word: 'MEME', coord: [ 6, 9 ] },
      { direction: 'h', position: 6, word: 'MEME', coord: [ 0, 3 ] },
      { direction: 'h', position: 6, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'h', position: 6, word: 'MEME', coord: [ 2, 5 ] },
      { direction: 'h', position: 6, word: 'MEME', coord: [ 3, 6 ] },
      { direction: 'h', position: 6, word: 'MEME', coord: [ 4, 7 ] },
      { direction: 'h', position: 6, word: 'MEME', coord: [ 5, 8 ] },
      { direction: 'h', position: 6, word: 'MEME', coord: [ 6, 9 ] },
      { direction: 'h', position: 7, word: 'MEME', coord: [ 0, 3 ] },
      { direction: 'h', position: 7, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'h', position: 7, word: 'MEME', coord: [ 2, 5 ] },
      { direction: 'h', position: 7, word: 'MEME', coord: [ 3, 6 ] },
      { direction: 'h', position: 7, word: 'MEME', coord: [ 4, 7 ] },
      { direction: 'h', position: 7, word: 'MEME', coord: [ 5, 8 ] },
      { direction: 'h', position: 7, word: 'MEME', coord: [ 6, 9 ] },
      { direction: 'h', position: 8, word: 'MEME', coord: [ 0, 3 ] },
      { direction: 'h', position: 8, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'h', position: 8, word: 'MEME', coord: [ 2, 5 ] },
      { direction: 'h', position: 8, word: 'MEME', coord: [ 3, 6 ] },
      { direction: 'h', position: 8, word: 'MEME', coord: [ 4, 7 ] },
      { direction: 'h', position: 8, word: 'MEME', coord: [ 5, 8 ] },
      { direction: 'h', position: 8, word: 'MEME', coord: [ 6, 9 ] },
      { direction: 'h', position: 9, word: 'MEME', coord: [ 0, 3 ] },
      { direction: 'h', position: 9, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'h', position: 9, word: 'MEME', coord: [ 2, 5 ] },
      { direction: 'h', position: 9, word: 'MEME', coord: [ 3, 6 ] },
      { direction: 'h', position: 9, word: 'MEME', coord: [ 4, 7 ] },
      { direction: 'h', position: 9, word: 'MEME', coord: [ 5, 8 ] },
      { direction: 'h', position: 9, word: 'MEME', coord: [ 6, 9 ] },
      { direction: 'v', position: 0, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'v', position: 0, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'v', position: 0, word: 'MEME', coord: [ 2, 5 ] },
      { direction: 'v', position: 0, word: 'MEME', coord: [ 3, 6 ] },
      { direction: 'v', position: 0, word: 'MEME', coord: [ 4, 7 ] },
      { direction: 'v', position: 0, word: 'MEME', coord: [ 5, 8 ] },
      { direction: 'v', position: 0, word: 'MEME', coord: [ 6, 9 ] },
      { direction: 'v', position: 1, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'v', position: 1, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'v', position: 1, word: 'MEME', coord: [ 2, 5 ] },
      { direction: 'v', position: 1, word: 'MEME', coord: [ 3, 6 ] },
      { direction: 'v', position: 1, word: 'MEME', coord: [ 4, 7 ] },
      { direction: 'v', position: 1, word: 'MEME', coord: [ 5, 8 ] },
      { direction: 'v', position: 1, word: 'MEME', coord: [ 6, 9 ] },
      { direction: 'v', position: 2, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'v', position: 2, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'v', position: 2, word: 'MEME', coord: [ 2, 5 ] },
      { direction: 'v', position: 2, word: 'MEME', coord: [ 3, 6 ] },
      { direction: 'v', position: 2, word: 'MEME', coord: [ 4, 7 ] },
      { direction: 'v', position: 2, word: 'MEME', coord: [ 5, 8 ] },
      { direction: 'v', position: 2, word: 'MEME', coord: [ 6, 9 ] },
      { direction: 'v', position: 3, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'v', position: 3, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'v', position: 3, word: 'MEME', coord: [ 2, 5 ] },
      { direction: 'v', position: 3, word: 'MEME', coord: [ 3, 6 ] },
      { direction: 'v', position: 3, word: 'MEME', coord: [ 4, 7 ] },
      { direction: 'v', position: 3, word: 'MEME', coord: [ 5, 8 ] },
      { direction: 'v', position: 3, word: 'MEME', coord: [ 6, 9 ] },
      { direction: 'v', position: 4, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'v', position: 4, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'v', position: 4, word: 'MEME', coord: [ 2, 5 ] },
      { direction: 'v', position: 4, word: 'MEME', coord: [ 3, 6 ] },
      { direction: 'v', position: 4, word: 'MEME', coord: [ 4, 7 ] },
      { direction: 'v', position: 4, word: 'MEME', coord: [ 5, 8 ] },
      { direction: 'v', position: 4, word: 'MEME', coord: [ 6, 9 ] },
      { direction: 'v', position: 5, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'v', position: 5, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'v', position: 5, word: 'MEME', coord: [ 2, 5 ] },
      { direction: 'v', position: 5, word: 'MEME', coord: [ 3, 6 ] },
      { direction: 'v', position: 5, word: 'MEME', coord: [ 4, 7 ] },
      { direction: 'v', position: 5, word: 'MEME', coord: [ 5, 8 ] },
      { direction: 'v', position: 5, word: 'MEME', coord: [ 6, 9 ] },
      { direction: 'v', position: 6, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'v', position: 6, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'v', position: 6, word: 'MEME', coord: [ 2, 5 ] },
      { direction: 'v', position: 6, word: 'MEME', coord: [ 3, 6 ] },
      { direction: 'v', position: 6, word: 'MEME', coord: [ 4, 7 ] },
      { direction: 'v', position: 6, word: 'MEME', coord: [ 5, 8 ] },
      { direction: 'v', position: 6, word: 'MEME', coord: [ 6, 9 ] },
      { direction: 'v', position: 7, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'v', position: 7, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'v', position: 7, word: 'MEME', coord: [ 2, 5 ] },
      { direction: 'v', position: 7, word: 'MEME', coord: [ 3, 6 ] },
      { direction: 'v', position: 7, word: 'MEME', coord: [ 4, 7 ] },
      { direction: 'v', position: 7, word: 'MEME', coord: [ 5, 8 ] },
      { direction: 'v', position: 7, word: 'MEME', coord: [ 6, 9 ] },
      { direction: 'v', position: 8, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'v', position: 8, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'v', position: 8, word: 'MEME', coord: [ 2, 5 ] },
      { direction: 'v', position: 8, word: 'MEME', coord: [ 3, 6 ] },
      { direction: 'v', position: 8, word: 'MEME', coord: [ 4, 7 ] },
      { direction: 'v', position: 8, word: 'MEME', coord: [ 5, 8 ] },
      { direction: 'v', position: 8, word: 'MEME', coord: [ 6, 9 ] },
      { direction: 'v', position: 9, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'v', position: 9, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'v', position: 9, word: 'MEME', coord: [ 2, 5 ] },
      { direction: 'v', position: 9, word: 'MEME', coord: [ 3, 6 ] },
      { direction: 'v', position: 9, word: 'MEME', coord: [ 4, 7 ] },
      { direction: 'v', position: 9, word: 'MEME', coord: [ 5, 8 ] },
      { direction: 'v', position: 9, word: 'MEME', coord: [ 6, 9 ] },
      { direction: 'd', position: 0, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'd', position: 0, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'd', position: 0, word: 'MEME', coord: [ 2, 5 ] },
      { direction: 'd', position: 0, word: 'MEME', coord: [ 3, 6 ] },
      { direction: 'd', position: 0, word: 'MEME', coord: [ 4, 7 ] },
      { direction: 'd', position: 0, word: 'MEME', coord: [ 5, 8 ] },
      { direction: 'd', position: 0, word: 'MEME', coord: [ 6, 9 ] },
      { direction: 'd', position: 1, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'd', position: 1, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'd', position: 1, word: 'MEME', coord: [ 2, 5 ] },
      { direction: 'd', position: 1, word: 'MEME', coord: [ 3, 6 ] },
      { direction: 'd', position: 1, word: 'MEME', coord: [ 4, 7 ] },
      { direction: 'd', position: 1, word: 'MEME', coord: [ 5, 8 ] },
      { direction: 'd', position: 1, word: 'MEME', coord: [ 6, 9 ] },
      { direction: 'd', position: 2, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'd', position: 2, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'd', position: 2, word: 'MEME', coord: [ 2, 5 ] },
      { direction: 'd', position: 2, word: 'MEME', coord: [ 3, 6 ] },
      { direction: 'd', position: 2, word: 'MEME', coord: [ 4, 7 ] },
      { direction: 'd', position: 2, word: 'MEME', coord: [ 5, 8 ] },
      { direction: 'd', position: 2, word: 'MEME', coord: [ 6, 9 ] },
      { direction: 'd', position: 3, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'd', position: 3, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'd', position: 3, word: 'MEME', coord: [ 2, 5 ] },
      { direction: 'd', position: 3, word: 'MEME', coord: [ 3, 6 ] },
      { direction: 'd', position: 3, word: 'MEME', coord: [ 4, 7 ] },
      { direction: 'd', position: 3, word: 'MEME', coord: [ 5, 8 ] },
      { direction: 'd', position: 3, word: 'MEME', coord: [ 6, 9 ] },
      { direction: 'd', position: 4, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'd', position: 4, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'd', position: 4, word: 'MEME', coord: [ 2, 5 ] },
      { direction: 'd', position: 4, word: 'MEME', coord: [ 3, 6 ] },
      { direction: 'd', position: 4, word: 'MEME', coord: [ 4, 7 ] },
      { direction: 'd', position: 4, word: 'MEME', coord: [ 5, 8 ] },
      { direction: 'd', position: 4, word: 'MEME', coord: [ 6, 9 ] },
      { direction: 'd', position: 5, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'd', position: 5, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'd', position: 5, word: 'MEME', coord: [ 2, 5 ] },
      { direction: 'd', position: 5, word: 'MEME', coord: [ 3, 6 ] },
      { direction: 'd', position: 5, word: 'MEME', coord: [ 4, 7 ] },
      { direction: 'd', position: 5, word: 'MEME', coord: [ 5, 8 ] },
      { direction: 'd', position: 5, word: 'MEME', coord: [ 6, 9 ] },
      { direction: 'd', position: 6, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'd', position: 6, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'd', position: 6, word: 'MEME', coord: [ 2, 5 ] },
      { direction: 'd', position: 6, word: 'MEME', coord: [ 3, 6 ] },
      { direction: 'd', position: 6, word: 'MEME', coord: [ 4, 7 ] },
      { direction: 'd', position: 6, word: 'MEME', coord: [ 5, 8 ] },
      { direction: 'd', position: 6, word: 'MEME', coord: [ 6, 9 ] },
      { direction: 'd', position: 7, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'd', position: 7, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'd', position: 7, word: 'MEME', coord: [ 2, 5 ] },
      { direction: 'd', position: 7, word: 'MEME', coord: [ 3, 6 ] },
      { direction: 'd', position: 7, word: 'MEME', coord: [ 4, 7 ] },
      { direction: 'd', position: 7, word: 'MEME', coord: [ 5, 8 ] },
      { direction: 'd', position: 7, word: 'MEME', coord: [ 6, 9 ] },
      { direction: 'd', position: 8, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'd', position: 8, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'd', position: 8, word: 'MEME', coord: [ 2, 5 ] },
      { direction: 'd', position: 8, word: 'MEME', coord: [ 3, 6 ] },
      { direction: 'd', position: 8, word: 'MEME', coord: [ 4, 7 ] },
      { direction: 'd', position: 8, word: 'MEME', coord: [ 5, 8 ] },
      { direction: 'd', position: 8, word: 'MEME', coord: [ 6, 9 ] },
      { direction: 'd', position: 9, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'd', position: 9, word: 'MEME', coord: [ 1, 4 ] },
      { direction: 'd', position: 9, word: 'MEME', coord: [ 2, 5 ] },
      { direction: 'd', position: 9, word: 'MEME', coord: [ 3, 6 ] },
      { direction: 'd', position: 9, word: 'MEME', coord: [ 4, 7 ] },
      { direction: 'd', position: 9, word: 'MEME', coord: [ 5, 8 ] },
      { direction: 'd', position: 9, word: 'MEME', coord: [ 6, 9 ] } ]);

    assert.eql(game.possiblePositions['YAHOO'], [ 
      { direction: 'h', position: 0, word: 'YAHOO', coord: [ 5, 9 ] },
      { direction: 'h', position: 0, word: 'YAHOO', coord: [ 5, 9 ] },
      { direction: 'h', position: 0, word: 'YAHOO', coord: [ 5, 9 ] },
      { direction: 'h', position: 0, word: 'YAHOO', coord: [ 5, 9 ] },
      { direction: 'h', position: 0, word: 'YAHOO', coord: [ 5, 9 ] },
      { direction: 'h', position: 0, word: 'YAHOO', coord: [ 5, 9 ] },
      { direction: 'h', position: 1, word: 'YAHOO', coord: [ 0, 4 ] },
      { direction: 'h', position: 1, word: 'YAHOO', coord: [ 1, 5 ] },
      { direction: 'h', position: 1, word: 'YAHOO', coord: [ 2, 6 ] },
      { direction: 'h', position: 1, word: 'YAHOO', coord: [ 3, 7 ] },
      { direction: 'h', position: 1, word: 'YAHOO', coord: [ 4, 8 ] },
      { direction: 'h', position: 1, word: 'YAHOO', coord: [ 5, 9 ] },
      { direction: 'h', position: 2, word: 'YAHOO', coord: [ 0, 4 ] },
      { direction: 'h', position: 2, word: 'YAHOO', coord: [ 1, 5 ] },
      { direction: 'h', position: 2, word: 'YAHOO', coord: [ 2, 6 ] },
      { direction: 'h', position: 2, word: 'YAHOO', coord: [ 3, 7 ] },
      { direction: 'h', position: 2, word: 'YAHOO', coord: [ 4, 8 ] },
      { direction: 'h', position: 2, word: 'YAHOO', coord: [ 5, 9 ] },
      { direction: 'h', position: 3, word: 'YAHOO', coord: [ 0, 4 ] },
      { direction: 'h', position: 3, word: 'YAHOO', coord: [ 1, 5 ] },
      { direction: 'h', position: 3, word: 'YAHOO', coord: [ 2, 6 ] },
      { direction: 'h', position: 3, word: 'YAHOO', coord: [ 3, 7 ] },
      { direction: 'h', position: 3, word: 'YAHOO', coord: [ 4, 8 ] },
      { direction: 'h', position: 3, word: 'YAHOO', coord: [ 5, 9 ] },
      { direction: 'h', position: 4, word: 'YAHOO', coord: [ 0, 4 ] },
      { direction: 'h', position: 4, word: 'YAHOO', coord: [ 1, 5 ] },
      { direction: 'h', position: 4, word: 'YAHOO', coord: [ 2, 6 ] },
      { direction: 'h', position: 4, word: 'YAHOO', coord: [ 3, 7 ] },
      { direction: 'h', position: 4, word: 'YAHOO', coord: [ 4, 8 ] },
      { direction: 'h', position: 4, word: 'YAHOO', coord: [ 5, 9 ] },
      { direction: 'h', position: 5, word: 'YAHOO', coord: [ 0, 4 ] },
      { direction: 'h', position: 5, word: 'YAHOO', coord: [ 1, 5 ] },
      { direction: 'h', position: 5, word: 'YAHOO', coord: [ 2, 6 ] },
      { direction: 'h', position: 5, word: 'YAHOO', coord: [ 3, 7 ] },
      { direction: 'h', position: 5, word: 'YAHOO', coord: [ 4, 8 ] },
      { direction: 'h', position: 5, word: 'YAHOO', coord: [ 5, 9 ] },
      { direction: 'h', position: 6, word: 'YAHOO', coord: [ 0, 4 ] },
      { direction: 'h', position: 6, word: 'YAHOO', coord: [ 1, 5 ] },
      { direction: 'h', position: 6, word: 'YAHOO', coord: [ 2, 6 ] },
      { direction: 'h', position: 6, word: 'YAHOO', coord: [ 3, 7 ] },
      { direction: 'h', position: 6, word: 'YAHOO', coord: [ 4, 8 ] },
      { direction: 'h', position: 6, word: 'YAHOO', coord: [ 5, 9 ] },
      { direction: 'h', position: 7, word: 'YAHOO', coord: [ 0, 4 ] },
      { direction: 'h', position: 7, word: 'YAHOO', coord: [ 1, 5 ] },
      { direction: 'h', position: 7, word: 'YAHOO', coord: [ 2, 6 ] },
      { direction: 'h', position: 7, word: 'YAHOO', coord: [ 3, 7 ] },
      { direction: 'h', position: 7, word: 'YAHOO', coord: [ 4, 8 ] },
      { direction: 'h', position: 7, word: 'YAHOO', coord: [ 5, 9 ] },
      { direction: 'h', position: 8, word: 'YAHOO', coord: [ 0, 4 ] },
      { direction: 'h', position: 8, word: 'YAHOO', coord: [ 1, 5 ] },
      { direction: 'h', position: 8, word: 'YAHOO', coord: [ 2, 6 ] },
      { direction: 'h', position: 8, word: 'YAHOO', coord: [ 3, 7 ] },
      { direction: 'h', position: 8, word: 'YAHOO', coord: [ 4, 8 ] },
      { direction: 'h', position: 8, word: 'YAHOO', coord: [ 5, 9 ] },
      { direction: 'h', position: 9, word: 'YAHOO', coord: [ 0, 4 ] },
      { direction: 'h', position: 9, word: 'YAHOO', coord: [ 1, 5 ] },
      { direction: 'h', position: 9, word: 'YAHOO', coord: [ 2, 6 ] },
      { direction: 'h', position: 9, word: 'YAHOO', coord: [ 3, 7 ] },
      { direction: 'h', position: 9, word: 'YAHOO', coord: [ 4, 8 ] },
      { direction: 'h', position: 9, word: 'YAHOO', coord: [ 5, 9 ] },
      { direction: 'v', position: 0, word: 'YAHOO', coord: [ 1, 5 ] },
      { direction: 'v', position: 0, word: 'YAHOO', coord: [ 1, 5 ] },
      { direction: 'v', position: 0, word: 'YAHOO', coord: [ 2, 6 ] },
      { direction: 'v', position: 0, word: 'YAHOO', coord: [ 3, 7 ] },
      { direction: 'v', position: 0, word: 'YAHOO', coord: [ 4, 8 ] },
      { direction: 'v', position: 0, word: 'YAHOO', coord: [ 5, 9 ] },
      { direction: 'v', position: 1, word: 'YAHOO', coord: [ 1, 5 ] },
      { direction: 'v', position: 1, word: 'YAHOO', coord: [ 1, 5 ] },
      { direction: 'v', position: 1, word: 'YAHOO', coord: [ 2, 6 ] },
      { direction: 'v', position: 1, word: 'YAHOO', coord: [ 3, 7 ] },
      { direction: 'v', position: 1, word: 'YAHOO', coord: [ 4, 8 ] },
      { direction: 'v', position: 1, word: 'YAHOO', coord: [ 5, 9 ] },
      { direction: 'v', position: 2, word: 'YAHOO', coord: [ 1, 5 ] },
      { direction: 'v', position: 2, word: 'YAHOO', coord: [ 1, 5 ] },
      { direction: 'v', position: 2, word: 'YAHOO', coord: [ 2, 6 ] },
      { direction: 'v', position: 2, word: 'YAHOO', coord: [ 3, 7 ] },
      { direction: 'v', position: 2, word: 'YAHOO', coord: [ 4, 8 ] },
      { direction: 'v', position: 2, word: 'YAHOO', coord: [ 5, 9 ] },
      { direction: 'v', position: 3, word: 'YAHOO', coord: [ 1, 5 ] },
      { direction: 'v', position: 3, word: 'YAHOO', coord: [ 1, 5 ] },
      { direction: 'v', position: 3, word: 'YAHOO', coord: [ 2, 6 ] },
      { direction: 'v', position: 3, word: 'YAHOO', coord: [ 3, 7 ] },
      { direction: 'v', position: 3, word: 'YAHOO', coord: [ 4, 8 ] },
      { direction: 'v', position: 3, word: 'YAHOO', coord: [ 5, 9 ] },
      { direction: 'v', position: 4, word: 'YAHOO', coord: [ 1, 5 ] },
      { direction: 'v', position: 4, word: 'YAHOO', coord: [ 1, 5 ] },
      { direction: 'v', position: 4, word: 'YAHOO', coord: [ 2, 6 ] },
      { direction: 'v', position: 4, word: 'YAHOO', coord: [ 3, 7 ] },
      { direction: 'v', position: 4, word: 'YAHOO', coord: [ 4, 8 ] },
      { direction: 'v', position: 4, word: 'YAHOO', coord: [ 5, 9 ] },
      { direction: 'v', position: 5, word: 'YAHOO', coord: [ 0, 4 ] },
      { direction: 'v', position: 5, word: 'YAHOO', coord: [ 1, 5 ] },
      { direction: 'v', position: 5, word: 'YAHOO', coord: [ 2, 6 ] },
      { direction: 'v', position: 5, word: 'YAHOO', coord: [ 3, 7 ] },
      { direction: 'v', position: 5, word: 'YAHOO', coord: [ 4, 8 ] },
      { direction: 'v', position: 5, word: 'YAHOO', coord: [ 5, 9 ] },
      { direction: 'v', position: 6, word: 'YAHOO', coord: [ 0, 4 ] },
      { direction: 'v', position: 6, word: 'YAHOO', coord: [ 1, 5 ] },
      { direction: 'v', position: 6, word: 'YAHOO', coord: [ 2, 6 ] },
      { direction: 'v', position: 6, word: 'YAHOO', coord: [ 3, 7 ] },
      { direction: 'v', position: 6, word: 'YAHOO', coord: [ 4, 8 ] },
      { direction: 'v', position: 6, word: 'YAHOO', coord: [ 5, 9 ] },
      { direction: 'v', position: 7, word: 'YAHOO', coord: [ 0, 4 ] },
      { direction: 'v', position: 7, word: 'YAHOO', coord: [ 1, 5 ] },
      { direction: 'v', position: 7, word: 'YAHOO', coord: [ 2, 6 ] },
      { direction: 'v', position: 7, word: 'YAHOO', coord: [ 3, 7 ] },
      { direction: 'v', position: 7, word: 'YAHOO', coord: [ 4, 8 ] },
      { direction: 'v', position: 7, word: 'YAHOO', coord: [ 5, 9 ] },
      { direction: 'v', position: 8, word: 'YAHOO', coord: [ 0, 4 ] },
      { direction: 'v', position: 8, word: 'YAHOO', coord: [ 1, 5 ] },
      { direction: 'v', position: 8, word: 'YAHOO', coord: [ 2, 6 ] },
      { direction: 'v', position: 8, word: 'YAHOO', coord: [ 3, 7 ] },
      { direction: 'v', position: 8, word: 'YAHOO', coord: [ 4, 8 ] },
      { direction: 'v', position: 8, word: 'YAHOO', coord: [ 5, 9 ] },
      { direction: 'v', position: 9, word: 'YAHOO', coord: [ 0, 4 ] },
      { direction: 'v', position: 9, word: 'YAHOO', coord: [ 1, 5 ] },
      { direction: 'v', position: 9, word: 'YAHOO', coord: [ 2, 6 ] },
      { direction: 'v', position: 9, word: 'YAHOO', coord: [ 3, 7 ] },
      { direction: 'v', position: 9, word: 'YAHOO', coord: [ 4, 8 ] },
      { direction: 'v', position: 9, word: 'YAHOO', coord: [ 5, 9 ] },
      { direction: 'd', position: 0, word: 'YAHOO', coord: [ 1, 5 ] },
      { direction: 'd', position: 0, word: 'YAHOO', coord: [ 1, 5 ] },
      { direction: 'd', position: 0, word: 'YAHOO', coord: [ 2, 6 ] },
      { direction: 'd', position: 0, word: 'YAHOO', coord: [ 3, 7 ] },
      { direction: 'd', position: 0, word: 'YAHOO', coord: [ 4, 8 ] },
      { direction: 'd', position: 0, word: 'YAHOO', coord: [ 5, 9 ] },
      { direction: 'd', position: 1, word: 'YAHOO', coord: [ 1, 5 ] },
      { direction: 'd', position: 1, word: 'YAHOO', coord: [ 1, 5 ] },
      { direction: 'd', position: 1, word: 'YAHOO', coord: [ 2, 6 ] },
      { direction: 'd', position: 1, word: 'YAHOO', coord: [ 3, 7 ] },
      { direction: 'd', position: 1, word: 'YAHOO', coord: [ 4, 8 ] },
      { direction: 'd', position: 1, word: 'YAHOO', coord: [ 5, 9 ] },
      { direction: 'd', position: 2, word: 'YAHOO', coord: [ 1, 5 ] },
      { direction: 'd', position: 2, word: 'YAHOO', coord: [ 1, 5 ] },
      { direction: 'd', position: 2, word: 'YAHOO', coord: [ 2, 6 ] },
      { direction: 'd', position: 2, word: 'YAHOO', coord: [ 3, 7 ] },
      { direction: 'd', position: 2, word: 'YAHOO', coord: [ 4, 8 ] },
      { direction: 'd', position: 2, word: 'YAHOO', coord: [ 5, 9 ] },
      { direction: 'd', position: 3, word: 'YAHOO', coord: [ 1, 5 ] },
      { direction: 'd', position: 3, word: 'YAHOO', coord: [ 1, 5 ] },
      { direction: 'd', position: 3, word: 'YAHOO', coord: [ 2, 6 ] },
      { direction: 'd', position: 3, word: 'YAHOO', coord: [ 3, 7 ] },
      { direction: 'd', position: 3, word: 'YAHOO', coord: [ 4, 8 ] },
      { direction: 'd', position: 3, word: 'YAHOO', coord: [ 5, 9 ] },
      { direction: 'd', position: 4, word: 'YAHOO', coord: [ 1, 5 ] },
      { direction: 'd', position: 4, word: 'YAHOO', coord: [ 1, 5 ] },
      { direction: 'd', position: 4, word: 'YAHOO', coord: [ 2, 6 ] },
      { direction: 'd', position: 4, word: 'YAHOO', coord: [ 3, 7 ] },
      { direction: 'd', position: 4, word: 'YAHOO', coord: [ 4, 8 ] },
      { direction: 'd', position: 4, word: 'YAHOO', coord: [ 5, 9 ] },
      { direction: 'd', position: 5, word: 'YAHOO', coord: [ 1, 5 ] },
      { direction: 'd', position: 5, word: 'YAHOO', coord: [ 1, 5 ] },
      { direction: 'd', position: 5, word: 'YAHOO', coord: [ 2, 6 ] },
      { direction: 'd', position: 5, word: 'YAHOO', coord: [ 3, 7 ] },
      { direction: 'd', position: 5, word: 'YAHOO', coord: [ 4, 8 ] },
      { direction: 'd', position: 5, word: 'YAHOO', coord: [ 5, 9 ] },
      { direction: 'd', position: 6, word: 'YAHOO', coord: [ 1, 5 ] },
      { direction: 'd', position: 6, word: 'YAHOO', coord: [ 1, 5 ] },
      { direction: 'd', position: 6, word: 'YAHOO', coord: [ 2, 6 ] },
      { direction: 'd', position: 6, word: 'YAHOO', coord: [ 3, 7 ] },
      { direction: 'd', position: 6, word: 'YAHOO', coord: [ 4, 8 ] },
      { direction: 'd', position: 6, word: 'YAHOO', coord: [ 5, 9 ] },
      { direction: 'd', position: 7, word: 'YAHOO', coord: [ 1, 5 ] },
      { direction: 'd', position: 7, word: 'YAHOO', coord: [ 1, 5 ] },
      { direction: 'd', position: 7, word: 'YAHOO', coord: [ 2, 6 ] },
      { direction: 'd', position: 7, word: 'YAHOO', coord: [ 3, 7 ] },
      { direction: 'd', position: 7, word: 'YAHOO', coord: [ 4, 8 ] },
      { direction: 'd', position: 7, word: 'YAHOO', coord: [ 5, 9 ] },
      { direction: 'd', position: 8, word: 'YAHOO', coord: [ 1, 5 ] },
      { direction: 'd', position: 8, word: 'YAHOO', coord: [ 1, 5 ] },
      { direction: 'd', position: 8, word: 'YAHOO', coord: [ 2, 6 ] },
      { direction: 'd', position: 8, word: 'YAHOO', coord: [ 3, 7 ] },
      { direction: 'd', position: 8, word: 'YAHOO', coord: [ 4, 8 ] },
      { direction: 'd', position: 8, word: 'YAHOO', coord: [ 5, 9 ] },
      { direction: 'd', position: 9, word: 'YAHOO', coord: [ 1, 5 ] },
      { direction: 'd', position: 9, word: 'YAHOO', coord: [ 1, 5 ] },
      { direction: 'd', position: 9, word: 'YAHOO', coord: [ 2, 6 ] },
      { direction: 'd', position: 9, word: 'YAHOO', coord: [ 3, 7 ] },
      { direction: 'd', position: 9, word: 'YAHOO', coord: [ 4, 8 ] },
      { direction: 'd', position: 9, word: 'YAHOO', coord: [ 5, 9 ] } ]);

    assert.eql(game.possiblePositions['POKER'], [ 
      { direction: 'h', position: 0, word: 'POKER', coord: [ 0, 4 ] },
      { direction: 'h', position: 0, word: 'POKER', coord: [ 1, 5 ] },
      { direction: 'h', position: 0, word: 'POKER', coord: [ 2, 6 ] },
      { direction: 'h', position: 0, word: 'POKER', coord: [ 3, 7 ] },
      { direction: 'h', position: 0, word: 'POKER', coord: [ 4, 8 ] },
      { direction: 'h', position: 0, word: 'POKER', coord: [ 5, 9 ] },
      { direction: 'h', position: 1, word: 'POKER', coord: [ 0, 4 ] },
      { direction: 'h', position: 1, word: 'POKER', coord: [ 1, 5 ] },
      { direction: 'h', position: 1, word: 'POKER', coord: [ 2, 6 ] },
      { direction: 'h', position: 1, word: 'POKER', coord: [ 3, 7 ] },
      { direction: 'h', position: 1, word: 'POKER', coord: [ 4, 8 ] },
      { direction: 'h', position: 1, word: 'POKER', coord: [ 5, 9 ] },
      { direction: 'h', position: 2, word: 'POKER', coord: [ 0, 4 ] },
      { direction: 'h', position: 2, word: 'POKER', coord: [ 1, 5 ] },
      { direction: 'h', position: 2, word: 'POKER', coord: [ 2, 6 ] },
      { direction: 'h', position: 2, word: 'POKER', coord: [ 3, 7 ] },
      { direction: 'h', position: 2, word: 'POKER', coord: [ 4, 8 ] },
      { direction: 'h', position: 2, word: 'POKER', coord: [ 5, 9 ] },
      { direction: 'h', position: 3, word: 'POKER', coord: [ 0, 4 ] },
      { direction: 'h', position: 3, word: 'POKER', coord: [ 1, 5 ] },
      { direction: 'h', position: 3, word: 'POKER', coord: [ 2, 6 ] },
      { direction: 'h', position: 3, word: 'POKER', coord: [ 3, 7 ] },
      { direction: 'h', position: 3, word: 'POKER', coord: [ 4, 8 ] },
      { direction: 'h', position: 3, word: 'POKER', coord: [ 5, 9 ] },
      { direction: 'h', position: 4, word: 'POKER', coord: [ 0, 4 ] },
      { direction: 'h', position: 4, word: 'POKER', coord: [ 1, 5 ] },
      { direction: 'h', position: 4, word: 'POKER', coord: [ 2, 6 ] },
      { direction: 'h', position: 4, word: 'POKER', coord: [ 3, 7 ] },
      { direction: 'h', position: 4, word: 'POKER', coord: [ 4, 8 ] },
      { direction: 'h', position: 4, word: 'POKER', coord: [ 5, 9 ] },
      { direction: 'h', position: 5, word: 'POKER', coord: [ 0, 4 ] },
      { direction: 'h', position: 5, word: 'POKER', coord: [ 1, 5 ] },
      { direction: 'h', position: 5, word: 'POKER', coord: [ 2, 6 ] },
      { direction: 'h', position: 5, word: 'POKER', coord: [ 3, 7 ] },
      { direction: 'h', position: 5, word: 'POKER', coord: [ 4, 8 ] },
      { direction: 'h', position: 5, word: 'POKER', coord: [ 5, 9 ] },
      { direction: 'h', position: 6, word: 'POKER', coord: [ 0, 4 ] },
      { direction: 'h', position: 6, word: 'POKER', coord: [ 1, 5 ] },
      { direction: 'h', position: 6, word: 'POKER', coord: [ 2, 6 ] },
      { direction: 'h', position: 6, word: 'POKER', coord: [ 3, 7 ] },
      { direction: 'h', position: 6, word: 'POKER', coord: [ 4, 8 ] },
      { direction: 'h', position: 6, word: 'POKER', coord: [ 5, 9 ] },
      { direction: 'h', position: 7, word: 'POKER', coord: [ 0, 4 ] },
      { direction: 'h', position: 7, word: 'POKER', coord: [ 1, 5 ] },
      { direction: 'h', position: 7, word: 'POKER', coord: [ 2, 6 ] },
      { direction: 'h', position: 7, word: 'POKER', coord: [ 3, 7 ] },
      { direction: 'h', position: 7, word: 'POKER', coord: [ 4, 8 ] },
      { direction: 'h', position: 7, word: 'POKER', coord: [ 5, 9 ] },
      { direction: 'h', position: 8, word: 'POKER', coord: [ 0, 4 ] },
      { direction: 'h', position: 8, word: 'POKER', coord: [ 1, 5 ] },
      { direction: 'h', position: 8, word: 'POKER', coord: [ 2, 6 ] },
      { direction: 'h', position: 8, word: 'POKER', coord: [ 3, 7 ] },
      { direction: 'h', position: 8, word: 'POKER', coord: [ 4, 8 ] },
      { direction: 'h', position: 8, word: 'POKER', coord: [ 5, 9 ] },
      { direction: 'h', position: 9, word: 'POKER', coord: [ 0, 4 ] },
      { direction: 'h', position: 9, word: 'POKER', coord: [ 1, 5 ] },
      { direction: 'h', position: 9, word: 'POKER', coord: [ 2, 6 ] },
      { direction: 'h', position: 9, word: 'POKER', coord: [ 3, 7 ] },
      { direction: 'h', position: 9, word: 'POKER', coord: [ 4, 8 ] },
      { direction: 'h', position: 9, word: 'POKER', coord: [ 5, 9 ] },
      { direction: 'v', position: 0, word: 'POKER', coord: [ 0, 4 ] },
      { direction: 'v', position: 0, word: 'POKER', coord: [ 1, 5 ] },
      { direction: 'v', position: 0, word: 'POKER', coord: [ 2, 6 ] },
      { direction: 'v', position: 0, word: 'POKER', coord: [ 3, 7 ] },
      { direction: 'v', position: 0, word: 'POKER', coord: [ 4, 8 ] },
      { direction: 'v', position: 0, word: 'POKER', coord: [ 5, 9 ] },
      { direction: 'v', position: 1, word: 'POKER', coord: [ 0, 4 ] },
      { direction: 'v', position: 1, word: 'POKER', coord: [ 1, 5 ] },
      { direction: 'v', position: 1, word: 'POKER', coord: [ 2, 6 ] },
      { direction: 'v', position: 1, word: 'POKER', coord: [ 3, 7 ] },
      { direction: 'v', position: 1, word: 'POKER', coord: [ 4, 8 ] },
      { direction: 'v', position: 1, word: 'POKER', coord: [ 5, 9 ] },
      { direction: 'v', position: 2, word: 'POKER', coord: [ 0, 4 ] },
      { direction: 'v', position: 2, word: 'POKER', coord: [ 1, 5 ] },
      { direction: 'v', position: 2, word: 'POKER', coord: [ 2, 6 ] },
      { direction: 'v', position: 2, word: 'POKER', coord: [ 3, 7 ] },
      { direction: 'v', position: 2, word: 'POKER', coord: [ 4, 8 ] },
      { direction: 'v', position: 2, word: 'POKER', coord: [ 5, 9 ] },
      { direction: 'v', position: 3, word: 'POKER', coord: [ 0, 4 ] },
      { direction: 'v', position: 3, word: 'POKER', coord: [ 1, 5 ] },
      { direction: 'v', position: 3, word: 'POKER', coord: [ 2, 6 ] },
      { direction: 'v', position: 3, word: 'POKER', coord: [ 3, 7 ] },
      { direction: 'v', position: 3, word: 'POKER', coord: [ 4, 8 ] },
      { direction: 'v', position: 3, word: 'POKER', coord: [ 5, 9 ] },
      { direction: 'v', position: 4, word: 'POKER', coord: [ 0, 4 ] },
      { direction: 'v', position: 4, word: 'POKER', coord: [ 1, 5 ] },
      { direction: 'v', position: 4, word: 'POKER', coord: [ 2, 6 ] },
      { direction: 'v', position: 4, word: 'POKER', coord: [ 3, 7 ] },
      { direction: 'v', position: 4, word: 'POKER', coord: [ 4, 8 ] },
      { direction: 'v', position: 4, word: 'POKER', coord: [ 5, 9 ] },
      { direction: 'v', position: 5, word: 'POKER', coord: [ 0, 4 ] },
      { direction: 'v', position: 5, word: 'POKER', coord: [ 1, 5 ] },
      { direction: 'v', position: 5, word: 'POKER', coord: [ 2, 6 ] },
      { direction: 'v', position: 5, word: 'POKER', coord: [ 3, 7 ] },
      { direction: 'v', position: 5, word: 'POKER', coord: [ 4, 8 ] },
      { direction: 'v', position: 5, word: 'POKER', coord: [ 5, 9 ] },
      { direction: 'v', position: 6, word: 'POKER', coord: [ 0, 4 ] },
      { direction: 'v', position: 6, word: 'POKER', coord: [ 1, 5 ] },
      { direction: 'v', position: 6, word: 'POKER', coord: [ 2, 6 ] },
      { direction: 'v', position: 6, word: 'POKER', coord: [ 3, 7 ] },
      { direction: 'v', position: 6, word: 'POKER', coord: [ 4, 8 ] },
      { direction: 'v', position: 6, word: 'POKER', coord: [ 5, 9 ] },
      { direction: 'v', position: 7, word: 'POKER', coord: [ 0, 4 ] },
      { direction: 'v', position: 7, word: 'POKER', coord: [ 1, 5 ] },
      { direction: 'v', position: 7, word: 'POKER', coord: [ 2, 6 ] },
      { direction: 'v', position: 7, word: 'POKER', coord: [ 3, 7 ] },
      { direction: 'v', position: 7, word: 'POKER', coord: [ 4, 8 ] },
      { direction: 'v', position: 7, word: 'POKER', coord: [ 5, 9 ] },
      { direction: 'v', position: 8, word: 'POKER', coord: [ 0, 4 ] },
      { direction: 'v', position: 8, word: 'POKER', coord: [ 1, 5 ] },
      { direction: 'v', position: 8, word: 'POKER', coord: [ 2, 6 ] },
      { direction: 'v', position: 8, word: 'POKER', coord: [ 3, 7 ] },
      { direction: 'v', position: 8, word: 'POKER', coord: [ 4, 8 ] },
      { direction: 'v', position: 8, word: 'POKER', coord: [ 5, 9 ] },
      { direction: 'v', position: 9, word: 'POKER', coord: [ 0, 4 ] },
      { direction: 'v', position: 9, word: 'POKER', coord: [ 1, 5 ] },
      { direction: 'v', position: 9, word: 'POKER', coord: [ 2, 6 ] },
      { direction: 'v', position: 9, word: 'POKER', coord: [ 3, 7 ] },
      { direction: 'v', position: 9, word: 'POKER', coord: [ 4, 8 ] },
      { direction: 'v', position: 9, word: 'POKER', coord: [ 5, 9 ] },
      { direction: 'd', position: 0, word: 'POKER', coord: [ 0, 4 ] },
      { direction: 'd', position: 0, word: 'POKER', coord: [ 1, 5 ] },
      { direction: 'd', position: 0, word: 'POKER', coord: [ 2, 6 ] },
      { direction: 'd', position: 0, word: 'POKER', coord: [ 3, 7 ] },
      { direction: 'd', position: 0, word: 'POKER', coord: [ 4, 8 ] },
      { direction: 'd', position: 0, word: 'POKER', coord: [ 5, 9 ] },
      { direction: 'd', position: 1, word: 'POKER', coord: [ 0, 4 ] },
      { direction: 'd', position: 1, word: 'POKER', coord: [ 1, 5 ] },
      { direction: 'd', position: 1, word: 'POKER', coord: [ 2, 6 ] },
      { direction: 'd', position: 1, word: 'POKER', coord: [ 3, 7 ] },
      { direction: 'd', position: 1, word: 'POKER', coord: [ 4, 8 ] },
      { direction: 'd', position: 1, word: 'POKER', coord: [ 5, 9 ] },
      { direction: 'd', position: 2, word: 'POKER', coord: [ 0, 4 ] },
      { direction: 'd', position: 2, word: 'POKER', coord: [ 1, 5 ] },
      { direction: 'd', position: 2, word: 'POKER', coord: [ 2, 6 ] },
      { direction: 'd', position: 2, word: 'POKER', coord: [ 3, 7 ] },
      { direction: 'd', position: 2, word: 'POKER', coord: [ 4, 8 ] },
      { direction: 'd', position: 2, word: 'POKER', coord: [ 5, 9 ] },
      { direction: 'd', position: 3, word: 'POKER', coord: [ 0, 4 ] },
      { direction: 'd', position: 3, word: 'POKER', coord: [ 1, 5 ] },
      { direction: 'd', position: 3, word: 'POKER', coord: [ 2, 6 ] },
      { direction: 'd', position: 3, word: 'POKER', coord: [ 3, 7 ] },
      { direction: 'd', position: 3, word: 'POKER', coord: [ 4, 8 ] },
      { direction: 'd', position: 3, word: 'POKER', coord: [ 5, 9 ] },
      { direction: 'd', position: 4, word: 'POKER', coord: [ 0, 4 ] },
      { direction: 'd', position: 4, word: 'POKER', coord: [ 1, 5 ] },
      { direction: 'd', position: 4, word: 'POKER', coord: [ 2, 6 ] },
      { direction: 'd', position: 4, word: 'POKER', coord: [ 3, 7 ] },
      { direction: 'd', position: 4, word: 'POKER', coord: [ 4, 8 ] },
      { direction: 'd', position: 4, word: 'POKER', coord: [ 5, 9 ] },
      { direction: 'd', position: 5, word: 'POKER', coord: [ 0, 4 ] },
      { direction: 'd', position: 5, word: 'POKER', coord: [ 1, 5 ] },
      { direction: 'd', position: 5, word: 'POKER', coord: [ 2, 6 ] },
      { direction: 'd', position: 5, word: 'POKER', coord: [ 3, 7 ] },
      { direction: 'd', position: 5, word: 'POKER', coord: [ 4, 8 ] },
      { direction: 'd', position: 5, word: 'POKER', coord: [ 5, 9 ] },
      { direction: 'd', position: 6, word: 'POKER', coord: [ 0, 4 ] },
      { direction: 'd', position: 6, word: 'POKER', coord: [ 1, 5 ] },
      { direction: 'd', position: 6, word: 'POKER', coord: [ 2, 6 ] },
      { direction: 'd', position: 6, word: 'POKER', coord: [ 3, 7 ] },
      { direction: 'd', position: 6, word: 'POKER', coord: [ 4, 8 ] },
      { direction: 'd', position: 6, word: 'POKER', coord: [ 5, 9 ] },
      { direction: 'd', position: 7, word: 'POKER', coord: [ 0, 4 ] },
      { direction: 'd', position: 7, word: 'POKER', coord: [ 1, 5 ] },
      { direction: 'd', position: 7, word: 'POKER', coord: [ 2, 6 ] },
      { direction: 'd', position: 7, word: 'POKER', coord: [ 3, 7 ] },
      { direction: 'd', position: 7, word: 'POKER', coord: [ 4, 8 ] },
      { direction: 'd', position: 7, word: 'POKER', coord: [ 5, 9 ] },
      { direction: 'd', position: 8, word: 'POKER', coord: [ 0, 4 ] },
      { direction: 'd', position: 8, word: 'POKER', coord: [ 1, 5 ] },
      { direction: 'd', position: 8, word: 'POKER', coord: [ 2, 6 ] },
      { direction: 'd', position: 8, word: 'POKER', coord: [ 3, 7 ] },
      { direction: 'd', position: 8, word: 'POKER', coord: [ 4, 8 ] },
      { direction: 'd', position: 8, word: 'POKER', coord: [ 5, 9 ] },
      { direction: 'd', position: 9, word: 'POKER', coord: [ 0, 4 ] },
      { direction: 'd', position: 9, word: 'POKER', coord: [ 1, 5 ] },
      { direction: 'd', position: 9, word: 'POKER', coord: [ 2, 6 ] },
      { direction: 'd', position: 9, word: 'POKER', coord: [ 3, 7 ] },
      { direction: 'd', position: 9, word: 'POKER', coord: [ 4, 8 ] },
      { direction: 'd', position: 9, word: 'POKER', coord: [ 5, 9 ] } ]);
    
  },
  'methods.registerWordsOnBoard().biggerWords': function () {
    game = new CrossWords();
    game.randomPositions = false;

    game.processTypedWords('felicidade,geladeiras,pernambuco,camilinhas,respondera,comunidade,institutos,curriculos,dicionario');
    game.registerWordsOnBoard();    

    assert.deepEqual(["DICIONARIO","CURRICULOS",
                      "INSTITUTOS","COMUNIDADE",
                      "RESPONDERA","CAMILINHAS",
                      "PERNAMBUCO","GELADEIRAS",
                      "FELICIDADE"], game.words);

    assert.deepEqual(
      ["DICIONARIO",
       "CURRICULOS",
       "INSTITUTOS",
       "COMUNIDADE",
       "RESPONDERA",
       "CAMILINHAS",
       "PERNAMBUCO",
       "GELADEIRAS",
       "FELICIDADE",
       "**********"], game.crossWord);


  },
  'methods.showBoard().noRandomPositionsPlusNoobieMode': function () {
    game = new CrossWords();
    game.prettyPrint = false;
    game.randomPositions = false;
    game.processTypedWords('yahoo,meme,poker');
    game.registerWordsOnBoard();
    assert.deepEqual(
      'P O K E R Y A H O O \n' + 
      'M E M E * * * * * * \n' + 
      '* * * * * * * * * * \n' + 
      '* * * * * * * * * * \n' + 
      '* * * * * * * * * * \n' + 
      '* * * * * * * * * * \n' + 
      '* * * * * * * * * * \n' + 
      '* * * * * * * * * * \n' + 
      '* * * * * * * * * * \n' + 
      '* * * * * * * * * * ', game.showBoard());
  },
  'methods.showBoard()': function () {
    game = new CrossWords();
    game.processTypedWords('yahoo,meme,poker');
    game.registerWordsOnBoard();

    assert.match(game.showBoard().length,/2(09|10)/);
  }
};

process.on('exit',function(){
   jsc.coverage();
});